FROM python:3.11-slim-buster

RUN apt-get update && \
    rm -rf /var/lib/apt/lists/* 

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8080"]
